name: Solsta Deployment Action
description: Deploy a release
inputs:
  solsta_client_id:
    description: Client ID to authenticate usage of Solid State Networks console tools
    required: true
    default: ""
  solsta_client_secret:
    description: Secret Key to authenticate usage of Solid State Networks console tools
    required: true
    default: ""
  console_version:
    description: Version of Solsta Console Tools to use
    required: true
    default: "6.1.1.12"
  scripts_version:
    description: Version of Solsta Deploy Scripts to use
    required: true
    default: "3.7.18"
  release_version:
    description: An environment variable or build parameter to use as a version within Solsta (optional)
    required: false
    default: ""
  working_directory:
    description: Relative path to folder containing deployable artifacts
    required: true
    default: ""
  target_product:
    description: Target product for deployment (case-sensitive)
    required: true
  target_environment:
    description: Target environment for deployment (case-sensitive)
    required: true
  target_repository:
    description: Target repository for deployment (case-sensitive)
    required: true

outputs:
  result:
    description: The state of the action, if processes completed successfully

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.solsta_client_id }}
    - ${{ inputs.solsta_client_secret }}
    - ${{ inputs.release_version }}
    - ${{ inputs.working_directory }}
    - ${{ inputs.console_version }}
    - ${{ inputs.scripts_version }}
    - ${{ inputs.target_product }}
    - ${{ inputs.target_environment }}
    - ${{ inputs.target_repository }}
branding:
  icon: "download-cloud"
  color: "yellow"
