name: Solsta Deployment Action
description: Deploy a release 
inputs:
  solsta_client_id:
    description: Client ID to authenticate usage of Solid State Networks console tools
    required: true
    default: ""
  solsta_client_secret:
    description: Secret Key to authenticate usage of Solid State Networks console tools
    required: true
    default: ""
  console_version:
    description: Version of Solsta Console Tools to use
    required: true
    default: "6.1.2.84"
  scripts_version:
    description: Version of Solsta Deploy Scripts to use
    required: true
    default: "3.7.30"
  release_version:
    description: An environment variable or build parameter to use as a version within Solsta (optional)
    required: false
    default: ""
  working_directory:
    description: Relative path to folder containing deployable artifacts
    required: true
    default: ""
  target_product:
    description: Target product for deployment (case-sensitive)
    required: true
  target_environment:
    description: Target environment for deployment (case-sensitive)
    required: true
  target_repository:
    description: Target repository for deployment (case-sensitive)
    required: true
  hidden_files:
    description: Hidden file relative path list. Format is ("path1" "path2" etc...)
    required: false
  sync_attributes:
    description: Set to 'true' to sync attributes from source files. 
    default: "false"
    required: false
  sync_timestamps:
    description: Set to 'true' to sync timestamps from source files. 
    default: "false"
    required: false
  executable_files:
    description: List of executable files in format '( "path1" "path2" etc.. )'
    required: false
  included_files:
    description: List of include file path masks, format is 'path1/;/*/path/*mask'
    required: false
  excluded_files:
    description: List of exclude file path masks, format is 'path1/;/*/path/*mask'
    required: false

outputs:
  result:
    description: The state of the action, if processes completed successfully

runs:
  using: 'composite'
  steps:
  - name: Solsta setup
    uses: snxd/deploy-github-setup-action@v2
    with:
      solsta_client_id: ${{ inputs.solsta_client_id }}
      solsta_client_secret: ${{ inputs.solsta_client_secret }}
      console_version: ${{ inputs.console_version }}
      scripts_version: ${{ inputs.scripts_version }}

  - name: Do Deploy
    shell: bash
    run: |
          # Run the script that creates a new release and deploys it
          solsta_extra_args=""
          if [ ! "${{ inputs.release_version }}" = "" ]; then
            solsta_extra_args+="--version=${{ inputs.release_version }}  "
          fi
          if [ ! "${{ inputs.hidden_files }}" = "" ]; then
            VAL=${{ inputs.hidden_files }}
            for i in ${VAL[@]} ; do
              solsta_extra_args+=" --hidden_files=$i "
            done
          fi
          sync_var="$(tr [A-Z] [a-z] <<< "${{ inputs.sync_attributes }}")"
          if [ "$sync_var" = "true" ]; then
              solsta_extra_args+=" --sync_attributes "
          fi
          sync_var="$(tr [A-Z] [a-z] <<< "${{ inputs.sync_timestamps }}")"
          if [ "$sync_var" = "true" ]; then
              solsta_extra_args+=" --sync_timestamps "
          fi
          if [ ! "${{ inputs.executable_files }}" = "" ]; then
            VAL=${{ inputs.executable_files }}
            for i in ${VAL[@]} ; do
              solsta_extra_args+=" --executable_files=$i "
            done
          fi
          if [ ! "${{ inputs.included_files }}" = "" ]; then
            solsta_extra_args+="--include=\"${{ inputs.included_files }}\" "
          fi
          if [ ! "${{ inputs.excluded_files }}" = "" ]; then
            solsta_extra_args+="--exclude=\"${{ inputs.excluded_files }}\" "
          fi
          eval "python solsta_work/release_deploy.py --autocreate --debug --console_credentials=solsta_work/client_credentials.json --console_directory=solsta_work/solsta_console/${{ inputs.console_version }}/console/ --process_default=API --product_name=\"${{ inputs.target_product }}\" --env_name=\"${{ inputs.target_environment }}\" --repository_name=\"${{ inputs.target_repository }}\" --source=\"${{ inputs.working_directory }}\" $solsta_extra_args"  
 
branding:
  icon: "download-cloud"
  color: "yellow"
